spring.application.name=metoa
spring.datasource.url=jdbc:mysql://localhost:3306/METOA_BD_COVOITURAGE
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.com.metoa.service.GeocodingService=DEBUG

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8089